create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  messages text not null,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

drop policy if exists "Allow public insert" on public.messages;
create policy "Allow public insert"
on public.messages
for insert
to anon, authenticated
with check (true);

drop policy if exists "Allow public read" on public.messages;
create policy "Allow public read"
on public.messages
for select
to anon, authenticated
using (true);